CREATE TABLE traveling_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    journal_id INTEGER
        REFERENCES traveling_journals(id) ON DELETE CASCADE NOT NULL,
    author_id INTEGER
        REFERENCES traveling_users(id) ON DELETE CASCADE NOT NULL
);
